[package]
name = "prism"
description = "Execution runtime: interprets plans and materializes the sandbox"
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[lib]
bench = false
doctest = true
name = "prism"
path = "src/lib.rs"
test = true

[dependencies]
plan = { workspace = true }
jinshu = { workspace = true }
ra = { workspace = true }
awq = { workspace = true }
