[package]
name = "cubefs"
description = "Deterministic COW filesystem using content-addressed Kpack recipes"
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true
keywords = ["cubefs", "cow", "filesystem", "storage"]

[dependencies]
x86_64 = { workspace = true }
