[package]
name = "zuu"
description = "Steganographic network layer: signal distortion and covert pressure"
keywords = ["zuu", "network", "steganography", "pressure"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
chacha20 = { workspace = true }
rand_chacha = { workspace = true }
rand_core = { workspace = true }
x25519-dalek = { workspace = true }
