[package]
name = "osiris"
description = "Guardian of transitions: process resurrection and state recovery"
keywords = ["osiris", "resurrection", "transition", "recovery"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
x86_64 = { workspace = true }
