[workspace]
members = [
    "awq",
    "hu",
    "ji",
    "jinshu",
    "kpack",
    "maat",
    "noun",
    "plan",
    "prism",
    "pulse",
    "ra",
    "re",
    "thot",
    "wa",
    "zuu",
]
resolver = "3"


[profile.dev]
opt-level = 2
panic = "abort"

[profile.release]
opt-level = 2
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
