[workspace]
members = [
    "abyss",
    "ammit",
    "anubis",
    "awq",
    "cubefs",
    "douat",
    "hamon",
    "horus",
    "hu",
    "ji",
    "jinshu",
    "kpack",
    "maat",
    "nil",
    "noun",
    "ocean",
    "osiris",
    "plan",
    "prism",
    "pulse",
    "ra",
    "re",
    "seth",
    "shekhmet",
    "thot",
    "wa",
    "zuu",
]
resolver = "3"

[profile.dev]
opt-level = 2
panic = "abort"

[profile.release]
opt-level = 2
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
