[workspace]
members = [
    "awq",
    "kpack",
    "jinshu",
    "maat",
    "noun",
    "plan",
    "ocean",
    "prism",
    "pulse",
    "ra",
    "re",
    "zuu",
]
resolver = "3"
[workspace.package]
license-file = "LICENSE"
edition = "2024"
publish = false
version = "0.0.0"

[workspace.dependencies]
kpack = { path = "kpack" }
noun = { path = "noun" }
ra = { path = "ra" }
plan = { path = "plan" }
jinshu = { path = "jinshu" }
prism = { path = "prism" }
awq = { path = "awq" }
zuu = { path = "zuu" }
blake3 = { version = "1.8.6", default-features = false }
heapless = { version = "0.9.3", default-features = false }
x86_64 = { version = "0.15.5", default-features = false, features = [
    "instructions",
    "abi_x86_interrupt",
] }
limine = { version = "0.6.5", default-features = false, features = [] }
linked_list_allocator = { version = "0.10.5", default-features = false, features = [
    "use_spin",
] }
x25519-dalek = { version = "3.0.0", default-features = false }
rand_core = { version = "0.10.1", default-features = false }
rand_chacha = { version = "0.10.0", default-features = false }
spin = { version = "0.12.3", default-features = false, features = [
    "mutex",
    "spin_mutex",
] }

lazy_static = { version = "1.4", default-features = false, features = [
    "spin_no_std",
] }
xmas-elf = "0.10.0"
os-terminal = { version = "0.7.4", default-features = false, features = [
    "bitmap",
] }

[profile.dev]
opt-level = 2
panic = "abort"

[profile.release]
opt-level = 2
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
