[package]
name = "hamon"
version = "0.1.0"
edition = "2024"
description = "Distributed Kpack job orchestration across a logical 3D hypercube"
license = "LicenseRef-ASAL"
license-file = "../LICENSE"
keywords = ["hamon", "orchestration", "kpack", "distributed"]
[dependencies]
x86_64 = { version = "0.15.5", default-features = false, features = [
    "instructions",
] }
