[package]
name = "hamon"
description = "Distributed Kpack job orchestration across a logical 3D hypercube"
keywords = ["hamon", "orchestration", "kpack", "distributed"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true
[dependencies]
x86_64 = { workspace = true }
