[package]
edition = "2024"
name = "ra"
version = "0.1.0"
description = "Application kernel: launches and supervises user-facing workloads"
keywords = ["ra", "kernel", "application", "workloads"]

[lib]
bench = false
doctest = true
name = "ra"
path = "src/lib.rs"
test = true

[dependencies]
jinshu = { path = "../jinshu", version = "0.1.0", default-features = false, features = [
] }
spin = { version = "0.12.3", default-features = false, features = [
    "mutex",
    "spin_mutex",
] }
heapless = { version = "0.9.3", default-features = false, features = [] }
x86_64 = { version = "0.15.5", default-features = false, features = [
    "instructions",
    "abi_x86_interrupt",
] }
