[package]
name = "hu"
description = "Library package manager: assembles plan recipes from reusable modules"
keywords = ["hu", "package", "manager", "plan"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
x86_64 = { workspace = true }
