[package]
name = "maat"
description = "The law of Amentys: weigh the Seal, endow caps, supervise pillars"
keywords = ["weigh", "law", "supervise", "endow"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
plan = { workspace = true }
jinshu = { workspace = true }
noun = { workspace = true }
prism = { workspace = true }
ra = { workspace = true }
x86_64 = { workspace = true }
limine = { workspace = true }
linked_list_allocator = { workspace = true }
