[alias]     # command aliases
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
kcheck = "clippy -- -D warnings -D clippy::undocumented_unsafe_blocks -D clippy::missing_safety_doc -D clippy::ptr_as_ptr -D clippy::transmute_ptr_to_ptr -D clippy::inline_always -D clippy::cast_possible_truncation -D clippy::cast_possible_wrap -D clippy::std_instead_of_core -W clippy::pedantic -W clippy::nursery -A clippy::missing_errors_doc -A clippy::panic -A clippy::expect_used"

[build]
warnings = "deny"             # adjust the effective lint level for warnings
jobs = 4                      # number of parallel jobs, defaults to # of CPUs
rustc = "rustc"               # the rust compiler tool
rustdoc = "rustdoc"           # the doc generator tool
target = "x86_64-unknown-none"     # build for the target triple (ignored by `cargo install`)
target-dir = "target"         # path of where to place generated artifacts
build-dir = "target"          # path of where to place intermediate build artifacts

[doc]
browser = "vivaldi"           # browser to use with `cargo doc --open`,
                              # overrides the `BROWSER` environment variable
[future-incompat-report]
frequency = 'always' # when to display a notification about a future incompat report

[cache]
auto-clean-frequency = "1 day"   # How often to perform automatic cache cleaning

[cargo-new]
vcs = "none"              # VCS to use ('git', 'hg', 'pijul', 'fossil', 'none')

[install]
root = "./"                # `cargo install` destination directory

[net]
retry = 3                   # network retries
git-fetch-with-cli = true   # use the `git` executable for git operations
offline = true              # do not access the network

[term]
quiet = false                    # whether cargo output is quiet
verbose = false                  # whether cargo provides verbose output
color = 'auto'                   # whether cargo colorizes output
hyperlinks = true                # whether cargo inserts links into output
unicode = true                   # whether cargo can render output using non-ASCII unicode characters
progress.when = 'auto'           # whether cargo shows progress bar
progress.width = 80              # width of progress bar
progress.term-integration = true # whether cargo reports progress to terminal emulator

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true
