[package]
name = "plan"
description = "Process manifest: defines layers and capabilities for sandboxed runs"
keywords = ["plan", "manifest", "sandbox", "capability"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
heapless = { workspace = true }
noun = { workspace = true }
blake3 = { workspace = true }