[package]
name = "pulse"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64 = { version = "0.15.5", default-features = false, features = [
    "instructions",
] }
x25519-dalek = { version = "3.0.0", default-features = false }
rand_core = { version = "0.10.1", default-features = false }
rand_chacha = { version = "0.10.0", default-features = false }
