[package]
name = "re"
description = "Supervisor kernel: low-level CPU control, interrupts, and memory"
keywords = ["re", "kernel", "supervisor", "memory"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true
[features]
default = ["fr"]
fr = []
us = []

[dependencies]
lazy_static = { workspace = true }
spin = { workspace = true }
x86_64 = { workspace = true }
limine = { workspace = true }
xmas-elf = { workspace = true }
os-terminal = { workspace = true }
linked_list_allocator = { workspace = true }
