[package]
name = "horus"
description = "Guardian of execution: oversees plan visibility and runtime defense"
keywords = ["horus", "execution", "guardian", "runtime"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
x86_64 = { workspace = true }
