[package]
name = "ocean"
description = "Process manifest: defines layers and capabilities for sandboxed runs"
keywords = ["ocean", "manifest", "sandbox", "capability"]
license-file.workspace = true
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
heapless = { workspace = true }
noun = { workspace = true }
zuu = { workspace = true }