[package]
name = "jinshu"
description = "Merkle-backed storage engine and Noun graph database on NVMe"
keywords = ["jinshu", "storage", "merkle", "database"]
license-file.workspace = true
edition.workspace = true
publish.workspace = true
version.workspace = true

[lib]
bench = false
doctest = true
name = "jinshu"
path = "src/lib.rs"
test = true

[dependencies]
kpack = { workspace = true }
noun = { workspace = true }
blake3 = { workspace = true }
heapless = { workspace = true }
